# Build code
FROM maven:3.5-jdk-8-alpine AS build
WORKDIR /builddir
COPY . /builddir
RUN mvn install -DskipTests

#Deploy code
FROM openjdk:8-jre-alpine
WORKDIR /app
COPY --from=build /builddir/target/api-client.jar .
EXPOSE 8882
ENTRYPOINT ["java","-jar","api-client.jar"]